variables:
  CACHE_VERSION: 20200522

schedules:
  # nightly builds to populate caches
  - cron: "3 0 * * Mon"
    displayName: Weekly midnight build
    branches:
      include:
      - master
    always: true
  - cron: "3 0 * * Tue-Sat,Sun"
    displayName: Daily midnight build
    branches:
      include:
      - master

jobs:
  - job: setup
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: none

      # Use this version of Python for syntax validation
      - task: UsePythonVersion@0
        displayName: Set up python
        inputs:
          versionSpec: 3.7

      # Download shallow clone and run syntax validation
      - bash: |
          mkdir repository
          cd repository
          echo Checking out $(Build.SourceBranch) from $(Build.Repository.Uri)
          git init
          git remote add origin $(Build.Repository.Uri)
          git fetch --depth 1 --no-recurse-submodules origin $(Build.SourceBranch)
          git checkout FETCH_HEAD
          python .azure-pipelines/syntax-validation.py
        displayName: Syntax validation
        workingDirectory: $(Pipeline.Workspace)

      # Set up date constants for caching in further build jobs
      - bash: |
          echo "##vso[task.setvariable variable=CURRENT_WEEK;isOutput=true]$(date +W%W)"
          echo "##vso[task.setvariable variable=TODAY_ISO;isOutput=true]$(date +%Y%m%d)"
        displayName: Set up build constants
        name: constants

  - template: ./.azure-pipelines/azure-pipelines-linux.yml

  - template: ./.azure-pipelines/azure-pipelines-mac.yml
