variables:
  CACHE_VERSION: 20201102
  ENABLE_CACHE: 0

schedules:
  # nightly builds to populate caches
  - cron: "3 0 * * Mon"
    displayName: Weekly midnight build
    branches:
      include:
      - main
    always: true
  - cron: "3 0 * * Tue-Sat,Sun"
    displayName: Daily midnight build
    branches:
      include:
      - main

jobs:
  - job: setup
    displayName: syntax validation
    pool:
      vmImage: ubuntu-20.04
    steps:
      - checkout: none

      # Use Python >=3.7 for syntax validation
      - task: UsePythonVersion@0
        displayName: Set up python
        inputs:
          versionSpec: 3.7

      # Run syntax validation on a shallow clone
      - bash: |
          mkdir repository
          cd repository
          echo Checking out $(Build.SourceBranch) from $(Build.Repository.Uri)
          git init
          git remote add origin $(Build.Repository.Uri)
          git fetch --depth 1 --no-recurse-submodules origin $(Build.SourceBranch)
          git checkout FETCH_HEAD
          python .azure-pipelines/syntax-validation.py
        displayName: Syntax validation

      # Set up date constants for caching in further build jobs
      - bash: |
          echo "##vso[task.setvariable variable=CURRENT_WEEK;isOutput=true]$(date +W%W)"
          echo "##vso[task.setvariable variable=TODAY_ISO;isOutput=true]$(date +%Y%m%d)"
          echo
          echo "Checking for waiting newsfragments:"
          cd repository/newsfragments
          \ls -1 --color=never | grep -v "^\([0-9]\+\|README\)\." && {
          echo "##vso[task.setvariable variable=NEWSFRAGMENT_WAITING;isOutput=true]true"
          } || {
          echo "none found"
          echo "##vso[task.setvariable variable=NEWSFRAGMENT_WAITING;isOutput=true]false"
          }
        displayName: Set up build constants
        name: constants

  - job: flake8
    displayName: flake8 validation
    dependsOn: setup
    condition: eq(dependencies.setup.outputs['constants.NEWSFRAGMENT_WAITING'], 'false')
    pool:
      vmImage: ubuntu-20.04
    steps:
      - checkout: none

      # Use Python >=3.7 for flake8
      - task: UsePythonVersion@0
        displayName: Set up python
        inputs:
          versionSpec: 3.7

      # Run flake8 validation on a shallow clone
      - bash: |
          pip install flake8 &
          mkdir repository
          cd repository
          echo Checking out $(Build.SourceBranch) from $(Build.Repository.Uri)
          git init
          git remote add origin $(Build.Repository.Uri)
          git fetch --depth 1 --no-recurse-submodules origin $(Build.SourceBranch)
          git checkout FETCH_HEAD
          wait
          python .azure-pipelines/flake8-validation.py
        displayName: Flake8 validation

  - template: .azure-pipelines/azure-pipelines-linux.yml

  - template: .azure-pipelines/azure-pipelines-mac.yml

  - template: .azure-pipelines/azure-pipelines-windows.yml
