addons:
  apt:
    packages:
      - libjpeg62

language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/build_dials
  timeout: 1000

jobs:
  include:
    - stage: build
      install:
         # Setup a base installation
         - ./.travis/setup-base

         # Inject DIALS
         - rm -rf $HOME/build_dials/modules/dials
         - mv $HOME/build/dials/dials $HOME/build_dials/modules/dials

         # Update CCTBX
         - $HOME/build_dials/modules/dials/.travis/clean-cctbx-dxtbx
         - $HOME/build_dials/modules/dials/.travis/update-cctbx-dxtbx

      before_script:
         # Enter CCTBX environment
         - cd $HOME/build_dials/build
         - cat setpaths.sh
         - . setpaths.sh

         # Prepare for the build step
         - libtbx.configure .

      script:
         # Parallel builds do not work. Only spend at most 40 minutes on a build.
         # This allows incremental building, so if the build can't be finished within the allotted time
         # it will be resumed from that point in the next build.
         - $HOME/build_dials/modules/dials/.travis/build-for 40m

    - name: "Syntax validation - Python 2.7"
      addons: false
      cache: false
      before_cache: false
      script:
         - python -m compileall -q *

    - name: "Syntax validation - Python 3.7"
      addons: false
      cache: false
      before_cache: false
      dist: xenial
      python: 3.7
      script:
         - python3 -m compileall -q *

    - stage: test
      before_script:
         # Inject DIALS. Again.
         - rm -rf $HOME/build_dials/modules/dials
         - mv $HOME/build/dials/dials $HOME/build_dials/modules/dials

         # Enter CCTBX environment
         - cd $HOME/build_dials/build
         - . setpaths.sh

         # If needed allow up to further 30 minutes worth of building time
         - $HOME/build_dials/modules/dials/.travis/build-for 30m if_required

      script:
         # Finally. Do what we are here for. Run tests. Yay.
         - cd $HOME/build_dials/modules/dials
         - pytest -ra -n 2 --runslow
         - .travis/check-working-directory-is-clean

    - name: "Build - Python 3.6"
         # Same as above really, but on Python 3 this time
      python: 3.6
      install:
         # Setup a base installation
         - ./.travis/setup-base3

         # Inject DIALS
         - rm -rf $HOME/build_dials/modules/dials
         - mv $HOME/build/dials/dials $HOME/build_dials/modules/dials

         # Update CCTBX
         - $HOME/build_dials/modules/dials/.travis/clean-cctbx-dxtbx
         - $HOME/build_dials/modules/dials/.travis/update-cctbx-dxtbx

      before_script:
         # Enter CCTBX environment
         - cd $HOME/build_dials/build
         - cat setpaths.sh
         - . setpaths.sh

         # Prepare for the build step
         - libtbx.configure .

      script:
         # Parallel builds do not work. Only spend at most 40 minutes on a build.
         # This allows incremental building, so if the build can't be finished within the allotted time
         # it will be resumed from that point in the next build.
         - $HOME/build_dials/modules/dials/.travis/build-for 40m

    - stage: python3
      name: "Test - Python 3.6"
         # Same as above really, but on Python 3 this time
      python: 3.6
      before_script:
         # Inject DIALS. Again.
         - rm -rf $HOME/build_dials/modules/dials
         - mv $HOME/build/dials/dials $HOME/build_dials/modules/dials

         # Enter CCTBX environment
         - cd $HOME/build_dials/build
         - . setpaths.sh

         # If needed allow up to further 30 minutes worth of building time
         - $HOME/build_dials/modules/dials/.travis/build-for 30m if_required

      script:
         # Finally. Do what we are here for. Run tests. Yay.
         - cd $HOME/build_dials/modules/dials
         - pytest -ra -n 2 --runslow --disable-warnings
         - .travis/check-working-directory-is-clean

    - name: "Flake8 - Python 2.7"
      addons: false
      cache: false
      before_cache: false
      script:
         - .travis/run-flake8
      if: type = pull_request

    - name: "Flake8 - Python 3.7"
      addons: false
      cache: false
      before_cache: false
      dist: xenial
      python: 3.7
      script:
         - .travis/run-flake8
      if: type = pull_request

before_cache:
  - $HOME/build_dials/modules/dials/.travis/clean-cctbx-dxtbx
  - cd $HOME
  - rm -rf $HOME/build_dials/modules/dials
