jobs:
- job: linux
  pool:
    vmImage: ubuntu-20.04
  variables:
    CURRENT_WEEK: $[ stageDependencies.prepare.setup.outputs['constants.CURRENT_WEEK'] ]
    TODAY_ISO: $[ stageDependencies.prepare.setup.outputs['constants.TODAY_ISO'] ]
  strategy:
    matrix:
      python36:
        PYTHON_VERSION: 3.6
#      python37:
#        PYTHON_VERSION: 3.7
#      python38:
#        PYTHON_VERSION: 3.8
  timeoutInMinutes: 90

  steps:
  - template: unix-build.yml
    parameters:
      conda_environment: .conda-envs/linux.txt
