jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  dependsOn: setup
  condition: eq(variables['ENABLE_CACHE'], '1')
  variables:
    CURRENT_WEEK: $[ dependencies.setup.outputs['constants.CURRENT_WEEK'] ]
    TODAY_ISO: $[ dependencies.setup.outputs['constants.TODAY_ISO'] ]
  strategy:
    matrix:
      python36:
        PYTHON_VERSION: 3.6
      python37:
        PYTHON_VERSION: 3.7
      python38:
        PYTHON_VERSION: 3.8
  timeoutInMinutes: 150

  steps:
  # Dependencies required for building gltbx
  - script: |
      sudo apt-get update
      sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
    displayName: Install dependencies

  - template: unix-build.yml
    parameters:
      conda_environment: .conda-envs/linux.txt

- job: linux_uncached
  pool:
    vmImage: ubuntu-latest
  dependsOn: setup
  condition: eq(variables['ENABLE_CACHE'], '0')
  variables:
    CURRENT_WEEK: $[ dependencies.setup.outputs['constants.CURRENT_WEEK'] ]
    TODAY_ISO: $[ dependencies.setup.outputs['constants.TODAY_ISO'] ]
    PYTHON_VERSION: 3.6
    REPOSITORIES_CACHED: false
    BASE_CACHED: false
    BUILD_CACHED: false
    DATA_CACHED: false
  timeoutInMinutes: 150

  steps:
  # Dependencies required for building gltbx
  - script: |
      sudo apt-get update
      sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
    displayName: Install dependencies

  - template: unix-build.yml
    parameters:
      conda_environment: .conda-envs/linux.txt
